apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-frontend
  template:
    metadata:
      labels:
        app: python-frontend
    spec:
      containers:
      - name: python-frontend
        image: nathancarrilho/frontend-python:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: python-frontend
spec:
  selector:
    app: python-frontend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer